MegaEventosVipRegister/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from clients import views

urlpatterns = [
    path('', views.error404, name='error404'),

    path('admin/', admin.site.urls),
    path('clientes/', include('clients.urls')),
    path('oficina/', include('office.urls')),

    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
    
] 
# + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

office/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required, permission_required

from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('pdf/<int:pk>/', login_required(views.GeneratePDF.as_view()) , name='GeneratePDF'),
    path('editar/<int:clave_id>', views.edit, name="edit"),
    path('eliminar/<int:clave_id>', views.delete, name="delete"),
    path('reciclaje/', views.reciclaje, name="reciclaje"),
    path('restaurar/<int:clave_id>', views.restore, name="restore"),
]

clients/models.py
from django.db import models

# Create your models here.

class Clients(models.Model):
    nombreCliente = models.CharField(max_length=100, null=False, blank=False)
    nombreHomenajeado = models.CharField(max_length=100, null=False, blank=False)
    celular = models.CharField(max_length=20, null=False, blank=False)
    barrioSector = models.CharField(max_length=200, null=False, blank=False)
    direccion = models.CharField(max_length=200, null=False, blank=False)
    fechaEvento = models.CharField(max_length=20, null=False, blank=False)
    horaInicio = models.CharField(max_length=20, null=False, blank=False)
    numeroPaquete = models.CharField(max_length=10, null=False, blank=False)
    cantidadNinos = models.CharField(max_length=100, null=False, blank=False)
    rangoEdad = models.CharField(max_length=100, null=False, blank=False)
    Recycle = models.BooleanField(default=False)

    class Meta:
        ordering = ['id']

office/models.py
from django.db import models

# Create your models here.


class Paquetes(models.Model):
    numeroPaquete = models.CharField(max_length=10, null=False, blank=False)
    nombrePaquete = models.CharField(max_length=200, null=False, blank=False)
    costoPaquete = models.CharField(max_length=100, null=False, blank=False)
    descripcionPaquete = models.CharField(max_length=250, null=False, blank=False)

    class Meta:
        ordering = ['id']

templates/edit.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="keywords"
        content="wrappixel, admin dashboard, html css dashboard, web dashboard, bootstrap 5 admin, bootstrap 5, css3 dashboard, bootstrap 5 dashboard, Nice lite admin bootstrap 5 dashboard, frontend, responsive bootstrap 5 admin template, Nice admin lite design, Nice admin lite dashboard bootstrap 5 dashboard template">
    <meta name="description"
        content="Nice Admin Lite is powerful and clean admin dashboard template, inpired from Bootstrap Framework">
    <meta name="robots" content="noindex,nofollow">
    <title>Edit</title>
    <!-- Favicon icon -->
    <link rel="icon" type="image/png" sizes="16x16" href="">
    <!-- Custom CSS -->
    <link href="{% static 'dist/css/style.min.css' %}" rel="stylesheet">
</head>

<body>
    <!-- Preloader - style you can find in spinners.css -->
    <div class="preloader">
        <div class="lds-ripple">
            <div class="lds-pos"></div>
            <div class="lds-pos"></div>
        </div>
    </div>
    <!-- Main wrapper - style you can find in pages.scss -->
    <div id="main-wrapper" data-navbarbg="skin6" data-theme="light" data-layout="vertical" data-sidebartype="full" data-boxed-layout="full">

        <!-- Page wrapper  -->
        <div class="page-wrapper">
    
            <!-- Bread crumb and right sidebar toggle -->
            <div class="page-breadcrumb">
                <div class="row">
                    <div class="col-5 align-self-center">
                        <!-- <h4 class="page-title">Editar informacion del Cliente</h4> -->
                    </div>
                    <div class="col-7 align-self-center">
                        <div class="d-flex align-items-center justify-content-end">
                            <nav aria-label="breadcrumb">
                                <ol class="breadcrumb">
                                    <li class="breadcrumb-item">
                                        <a href="{% url 'home' %}">Home</a>
                                    </li>
                                    <li class="breadcrumb-item active" aria-current="page">Profile</li>
                                </ol>
                            </nav>
                        </div>
                    </div>
                </div>
            </div>
    
            <!-- Container fluid  -->
    
            <div class="container-fluid">
                <!-- Start Page Content -->
                <div class="row">

                    <div class="col-lg-2 col-xlg-3"></div>

                    <div class="col-lg-8 col-xlg-9">
                        <div class="card">
                            <div class="card-body">

                                <form method="POST" class="row g-3">
                                    {% csrf_token %}
                                    <div class="text-center mb-5 mt-4">
                                        <h3 class="page-title">Editar informacion del Cliente</h3>
                                    </div>

                                    <div class="col-md-6">
                                        <label class="form-label">Nombre</label>
                                        <input class="form-control form-control-line" type="text" name="nombreCliente" value="{{instancia.nombreCliente}}" maxlength="100" required="" id="id_nombreCliente">
                                    </div>
                                    <div class="col-md-6">
                                        <label class="form-label">Nombre Homenajead@</label>
                                        <input class="form-control form-control-line" type="text" name="nombreHomenajeado" value="{{instancia.nombreHomenajeado}}" maxlength="100" required="" id="id_nombreHomenajeado">
                                    </div>
                                    <div class="col-md-6">
                                        <label class="form-label">Celular</label>
                                        <input class="form-control form-control-line" type="text" name="celular" value="{{instancia.celular}}" maxlength="20" required="" id="id_celular">
                                    </div>
                                    <div class="col-md-6">
                                        <label class="form-label">Barrio / Sector</label>
                                        <input class="form-control form-control-line" type="text" name="barrioSector" value="{{instancia.barrioSector}}" maxlength="200" required="" id="id_barrioSector">
                                    </div>
                                    <div class="col-md-6">
                                        <label class="form-label">Dirección</label>
                                        <input class="form-control form-control-line" type="text" name="direccion" value="{{instancia.direccion}}" maxlength="200" required="" id="id_direccion">
                                    </div>
                                    <div class="col-md-6">
                                        <label class="form-label">Fecha Evento</label>
                                        <input class="form-control form-control-line" type="text" name="fechaEvento" value="{{instancia.fechaEvento}}" maxlength="20" required="" id="id_fechaEvento">
                                    </div>
                                    <div class="col-md-6">
                                        <label class="form-label">Hora Inicio</label>
                                        <input class="form-control form-control-line" type="text" name="horaInicio" value="{{instancia.horaInicio}}" maxlength="20" required="" id="id_horaInicio">
                                    </div>
                                    <div class="col-md-6">
                                        <label class="form-label">Paquete</label>
                                        <input class="form-control form-control-line" type="text" name="numeroPaquete" value="{{instancia.numeroPaquete}}" maxlength="10" required="" id="id_numeroPaquete">
                                    </div>
                                    <div class="col-md-6">
                                        <label class="form-label">Niños</label>
                                        <input class="form-control form-control-line" type="text" name="cantidadNinos" value="{{instancia.cantidadNinos}}" maxlength="100" required="" id="id_cantidadNinos">
                                    </div>
                                    <div class="col-md-6">
                                        <label class="form-label">Edades</label>
                                        <input class="form-control" type="text" name="rangoEdad" value="{{instancia.rangoEdad}}" maxlength="100" required="" id="id_rangoEdad">
                                    </div>

                                    <div class="d-flex justify-content-center mt-5">
                                        <button style="margin-right: 3em;" class="btn btn-primary mr-3" type="submit">Editar</button>
                                        <a class="btn btn-secondary" href="{% url 'home' %}" type="button">Volver</a>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- End PAge Content -->
            </div>
    
            <!-- End Container fluid  -->
    
            <!-- footer -->
            <footer class="footer text-center">
                All Rights Reserved Mega Eventos Vip. Developed by
                <a href="https://www.wrappixel.com">Mateo</a>.
            </footer>
            <!-- End footer -->
        </div>
        <!-- End Page wrapper  -->
    </div>

    <!-- All Jquery -->
    <script src="{% static 'assets/libs/jquery/dist/jquery.min.js' %}"></script>
    <!-- Bootstrap tether Core JavaScript -->
    <script src="{% static 'assets/libs/bootstrap/dist/js/bootstrap.bundle.min.js' %}"></script>
    <!-- slimscrollbar scrollbar JavaScript -->
    <script src="{% static 'assets/extra-libs/sparkline/sparkline.js' %}"></script>
    <!--Wave Effects -->
    <script src="{% static 'dist/js/waves.js' %}"></script>
    <!--Menu sidebar -->
    <script src="{% static 'dist/js/sidebarmenu.js' %}"></script>
    <!--Custom JavaScript -->
    <script src="{% static 'dist/js/custom.min.js' %}"></script>
</body>

</html>

templates/error-404.html
{% load static %}
<!DOCTYPE html>
<html dir="ltr">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="keywords"
        content="wrappixel, admin dashboard, html css dashboard, web dashboard, bootstrap 5 admin, bootstrap 5, css3 dashboard, bootstrap 5 dashboard, Nice lite admin bootstrap 5 dashboard, frontend, responsive bootstrap 5 admin template, Nice admin lite design, Nice admin lite dashboard bootstrap 5 dashboard template">
    <meta name="description"
        content="Nice Admin Lite is powerful and clean admin dashboard template, inpired from Bootstrap Framework">
    <meta name="robots" content="noindex,nofollow">
    <title>Error 404</title>
    <link rel="canonical" href="https://www.wrappixel.com/templates/niceadmin-lite/" />
    <!-- Favicon icon -->
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'assets/images/favicon.png' %}">
    <!-- Custom CSS -->
    <link href="{% static 'dist/css/style.min.css' %}" rel="stylesheet">
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
<![endif]-->
</head>

<body>
    <div class="main-wrapper">
        <!-- ============================================================== -->
        <!-- Preloader - style you can find in spinners.css -->
        <!-- ============================================================== -->
        <div class="preloader">
            <div class="lds-ripple">
                <div class="lds-pos"></div>
                <div class="lds-pos"></div>
            </div>
        </div>
        <!-- ============================================================== -->
        <!-- Preloader - style you can find in spinners.css -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->
        <!-- Login box.scss -->
        <!-- ============================================================== -->
        <div class="error-box">
            <div class="error-body text-center">
                <h1 class="error-title text-primary">404</h1>
                <h3 class="text-uppercase error-subtitle">PAGE NOT FOUND !</h3>
                <p class="text-muted mt-4 mb-4">YOU SEEM TO BE TRYING TO FIND HIS WAY HOME</p>
                <a href="{% url 'index' %}" class="btn btn-primary btn-rounded waves-effect waves-light mb-5 text-white">Back to home</a>
            </div>
        </div>
        <!-- ============================================================== -->
        <!-- Login box.scss -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->
        <!-- Page wrapper scss in scafholding.scss -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->
        <!-- Page wrapper scss in scafholding.scss -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->
        <!-- Right Sidebar -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->
        <!-- Right Sidebar -->
        <!-- ============================================================== -->
    </div>
    <!-- ============================================================== -->
    <!-- All Required js -->
    <!-- ============================================================== -->
    <script src="{% static 'assets/libs/jquery/dist/jquery.min.js' %}"></script>
    <!-- Bootstrap tether Core JavaScript -->
    <script src="{% static 'assets/libs/bootstrap/dist/js/bootstrap.bundle.min.js' %}"></script>
    <!-- ============================================================== -->
    <!-- This page plugin js -->
    <!-- ============================================================== -->
    <script>
        $(".preloader").fadeOut();
    </script>
</body>

</html>

templates/pdf.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>

  <style>
    h1{
        line-height: normal;
        text-transform: uppercase;
        font-size: 16px;
    }

    span{
        font-weight: normal;
    }
    .tablecustom {
        width: 100%;
    }

    .tablecustom td {
        text-align: left;
        border: 1px solid #000;
        border-collapse: collapse;
        margin: 1em;
    }

    img{
        height: 200px;
    }
      

  </style>

</head>
<body>

    <table>
        <tr>
            <td>
                <img src="{% static 'images/logopdf.jpeg' %}" alt="">
            </td>
            <td>
                <h1>CÓDIGO DE LA ORDEN: {{clients.id}}</h1>
                <h1>HORARIO DEL EVENTO: {{clients.horaInicio}}</h1>
                <h1>RECREADORES: </h1>
            </td>
        </tr>
    </table>

    <br><br><br><br>

    <table class="tablecustom">
        <tr>
            <td>
                <h1 style="padding-top: 10px;">NOMBRE DEL CLIENTE: <span>{{clients.nombreCliente}}</span></h1>
                <h1>TEL: <span>{{clients.celular}}</span></h1>
                <h1>BARRIO / SECTOR: <span>{{clients.barrioSector}}</span></h1>
                <h1>FECHA DEL EVENTO: <span>{{clients.fechaEvento}}</span></h1>
                <h1 style="padding-bottom: 10px;">NIÑOS: <span>{{clients.cantidadNinos}}</span></h1>
                
            </td>
            <td>
                <h1 style="padding-top: 10px;">NOMBRE HOMENAJEAD@: <span>{{clients.nombreHomenajeado}}</span></h1>
                <h1>PAQUETE: <span>{{clients.numeroPaquete}}</span></h1>
                <h1>DIRECCIÓN: <span>{{clients.direccion}}</span></h1>
                <h1>HORA DE INICIO: <span>{{clients.horaInicio}}</span></h1>
                <h1 style="padding-bottom: 10px;">EDADES: <span>{{clients.rangoEdad}}</span></h1>
            </td>
        </tr>
    </table>

    <br><br><br>

    <table class="tablecustom">
        <tr>
            {% for paquete in paquetes %}
                {% if paquete.numeroPaquete == clients.numeroPaquete %}
                    <td>
                        <h1 style="padding-bottom: 10px; padding-top: 10px;" style="padding-top: 10px;">DESCRIPCIÓN DEL SERVICIO: <span>{{paquete.descripcionPaquete}}</span></h1>
                    </td>
                {% endif %}
            {% endfor %}
        </tr>
    </table>

    <br><br><br>

    <table class="tablecustom">
        <tr>
            {% for paquete in paquetes %}
                {% if paquete.numeroPaquete == clients.numeroPaquete %}
                    <td>
                        <h1 style="padding-top: 10px;">COSTO DEL SERVICIO: ${{paquete.costoPaquete}}</h1>
                        <h1 style="padding-bottom: 10px;">ABONO: </h1>
                    </td>
                    <td>
                        <h1 style="padding-top: 10px;">SALDO PENDIENTE: </h1>
                        <h1 style="padding-bottom: 10px;">FECHA DEL ABONO: </h1>
                    </td>
                {% endif %}
            {% endfor %}
        </tr>
    </table>

    <br><br><br>

    <table>
        <tr>
            <h1>
                <span>
                    En este espacio queremos que como cliente nos haga saber su nivel de satisfacción mediante una pequeña calificación. Donde 1 es la menor calificación y 5 la mejor. (Si tiene alguna observación positiva o negativa, permítase hacerla en la parte posterior de la hoja)
                </span>
            </h1>
            <br>
            <td>
                <h1>SERVICIO. __</h1>
            </td>
            <td>
                <h1>ASESORÍA. __</h1>
            </td>
            <td>
                <h1>PUNTUALIDAD. __</h1>
            </td>
            <td>
                <h1>PRESENTACIÓN. __</h1>
            </td>
        </tr>
    </table>

    <br><br><br><br>
    <h2>_______________________________</h2>
    <h2>Nombre y firma del cliente</h2>
</body>
</html>

templates/recycle.html
{% extends 'index.html' %}
{% load static %}

{%block contenttitle %}
    <!-- Bread crumb and right sidebar toggle -->
    <div class="page-breadcrumb">
        <div class="row">
            <div class="col-5 align-self-center">
                <h4 class="page-title">Papelera de reciclaje</h4>
            </div>
            <div class="col-7 align-self-center">
                <div class="d-flex align-items-center justify-content-end">
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item">
                                <a href="#">Home</a>
                            </li>
                            <li class="breadcrumb-item active" aria-current="page">Reciclaje</li>
                        </ol>
                    </nav>
                </div>
            </div>
        </div>
    </div>
{%endblock contenttitle%}

    <!-- End Bread crumb and right sidebar toggle -->

    <!-- Container fluid  -->
{%block content %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title">Lista de clientes eliminados</h4>
                    </div>
                    <div class="table-responsive">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th scope="col">#</th>
                                    <th scope="col">Nombre</th>
                                    <th scope="col">Nombre Homenajead@</th>
                                    <th scope="col">Celular</th>
                                    <th scope="col">Barrio / Sector</th>
                                    <th scope="col">Dirección</th>
                                    <th scope="col">Fecha Evento</th>
                                    <th scope="col">Hora Inicio</th>
                                    <th scope="col">Paquete</th>
                                    <th scope="col">Niños</th>
                                    <th scope="col">Edades</th>
                                    <th scope="col">Restaurar</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for client in clients %}
                                    {% if client.Recycle is True %}
                                        <tr class="table-info">
                                            <td>{{client.id}}</td>
                                            <td>{{client.nombreCliente}}</td>
                                            <td>{{client.nombreHomenajeado}}</td>
                                            <td>{{client.celular}}</td>
                                            <td>{{client.barrioSector}}</td>
                                            <td>{{client.direccion}}</td>
                                            <td>{{client.fechaEvento}}</td>
                                            <td>{{client.horaInicio}}</td>
                                            <td>{{client.numeroPaquete}}</td>
                                            <td>{{client.cantidadNinos}}</td>
                                            <td>{{client.rangoEdad}}</td>
                                            <td><a href="/oficina/restaurar/{{ client.id }}" onClick="return confirm('¿Seguro que quieres borrar a {{client.nombreCliente}}?');" ><button class="btn btn-success text-white"><i class="fas fa-trash-restore"></i></button></a></td>
                                        </tr>
                                    {% endif %}
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
{%endblock%}
            
<!-- End Container fluid  -->

templates/registroServicio.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Registro del servicio</title>

    <!-- Font Icon -->
    <link rel="stylesheet" href="{% static 'fonts/material-icon/css/material-design-iconic-font.min.css' %}">

    <!-- Main css -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">



    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/timepicker/1.3.5/jquery.timepicker.min.css">


    <style>
        .ui-timepicker-standard .ui-state-hover{
            background: linear-gradient(to left, #943883, #511575);
        }
    </style>

</head>
<body>

    <div class="nav">
        <input type="checkbox" id="nav-check">
        <div class="nav-header">
          <div class="nav-title">
            <h2>Mega <span>Eventos</span> Vip</h2>
          </div>
        </div>
        <div class="nav-btn">
          <label for="nav-check">
            <span></span>
            <span></span>
            <span></span>
          </label>
        </div>
      
        <div class="nav-links">
            <a href="{% url 'login' %}" class="login-btn">Login</a>
        </div>
      </div>

    <div class="main">

        <section class="signup">
            <div class="container">
                <div class="signup-content">
                    <form method="POST" id="signup-form" class="signup-form">
                        {% csrf_token %}
                        <h2 class="form-title">Registro del servicio</h2>
                        <div class="form-group">
                            <input type="text" class="form-input" name="nombreCliente" maxlength="100" required="" id="id_nombreCliente" placeholder="Nombre completo del cliente"/>
                        </div>
                        <div class="form-group">
                            <input type="text" class="form-input" name="nombreHomenajeado" maxlength="100" required="" id="id_nombreHomenajeado" placeholder="Nombre completo Homenajead@"/>
                        </div>
                        <div class="form-group">
                            <input type="text" class="form-input" name="celular" maxlength="20" required="" id="id_celular" placeholder="Celular"/>
                        </div>
                        <div class="form-group">
                            <input type="text" class="form-input" name="barrioSector" maxlength="200" required="" id="id_barrioSector" placeholder="Barrio / Sector"/>
                        </div>
                        <div class="form-group">
                            <input type="text" class="form-input" name="direccion" maxlength="200" required="" id="id_direccion" placeholder="Dirección"/>
                        </div>
                        <div class="form-group">
                            <input type="text" class="form-input" name="fechaEvento" maxlength="20" required="" id="id_fechaEvento" placeholder="Fecha Evento"/>
                        </div>
                        <div class="form-group">
                            <input type="text" class="form-input" name="horaInicio" maxlength="20" required="" id="id_horaInicio" autocomplete="off" placeholder="Hora de inicio"/>
                        </div>
                        <div class="form-group">
                            <input type="text" class="form-input" name="numeroPaquete" maxlength="10" required="" id="id_numeroPaquete" placeholder="Número del paquete"/>
                        </div>
                        <div class="form-group">
                            <input type="text" class="form-input" name="cantidadNinos" maxlength="100" required="" id="id_cantidadNinos" placeholder="Cantidad de niños"/>
                        </div>
                        <div class="form-group">
                            <input type="text" class="form-input" name="rangoEdad" maxlength="100" required="" id="id_rangoEdad" placeholder="Rango de edades"/>
                        </div>

                        <div class="form-group">
                            <input type="submit" name="submit" id="submit" class="form-submit" value="Enviar"/>
                        </div>
                    </form>
                </div>
            </div>
        </section>

    </div>

    <!-- JS -->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>

    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

    <script src="//cdnjs.cloudflare.com/ajax/libs/timepicker/1.3.5/jquery.timepicker.min.js"></script>

    <script>
        $(function(){
            $("#id_fechaEvento").datepicker();
        });
    </script>

    <script>
        $(document).ready(function(){
            $('#id_horaInicio').timepicker({
                timeFormat: 'h:mm p',
                interval: 15,
                minTime: '10',
                maxTime: '6:00pm',
                // startTime: '10:00',
                // defaultTime: '11',
                scrollbar: true
            });
        });
    </script>

    <!-- <script>
        // close the toggle menu if user clicks outside of the menu

        $(document).click(function(event) {
        if(
            $('.toggle > input').is(':checked') &&
            !$(event.target).parents('.toggle').is('.toggle')
        ) {
            $('.toggle > input').prop('checked', false);
        }
        })
    </script> -->

</body>
</html>